### ISSUE TITLE
Create MVPs against sketch design mock.

### ISSUE THREAD

**Issue by rivernews** [PrincipleZ/SI699_Tokachu#8]
The current sketch design needs significant simplification in order to drive the dev process. To stay focus and make sure we're progressing, create small MVP each time for the current important, prioritized feature that is not yet done based on the sketch.app design.

**Comment by rivernews** [comment]
[Link to sketch file](https://drive.google.com/open?id=1oPF3pkAEzTSaV51OYy41QvQI91-rjfVK&authuser=shaungc@umich.edu) in team's google drive.

**Comment by rivernews** [comment]
[Dev roadmap](https://drive.google.com/open?id=14NBenfF6bQrPg27SL47CvucyRWzgmkDR&authuser=shaungc@umich.edu) for the near future.

**Comment by rivernews** [comment]
Visit the [repo project board](https://github.com/PrincipleZ/SI699_Tokachu/projects/1) for a full view of todo cards (like Trello!).

Can also [link a commit/pull request to an issue](https://stackoverflow.com/questions/1687262/link-to-the-issue-number-on-github-within-a-commit-message).

**Comment by rivernews** [comment]
# Roadmap

Basic Logics

- [ ] Event (related pages: explore, events)
  - [ ] Basic Master-Detail view
  - [ ] (optional) More user input fields --clear_expectation_needed
  - [ ] (optional) More refined logics (avatars in event detail page links to conversation, etc.) --clear_expectation_needed
- [ ] Account (related pages: account): show username only
- [ ] Conversation (related pages: conversation...)
- [ ] Onboarding & Registration

UI Improvements

- [ ] Event List page --clear_expectation_needed
- [ ] Event Detail page --clear_expectation_needed
- [ ] Account Page
